### ISSUE TITLE
ERROR Unable to get failures in

### ISSUE THREAD

**Issue by ya-petrov** [fail2ban/fail2ban#1769]
Hello. 
Periodically, an error occurs:

[~] tail -1 /logs/fail2ban.filter 
May  7 06:01:00 fail2ban.filter[14160]: ERROR Unable to get failures in /data/logs/linux/current

After the occurrence of this error, the processing of rules is terminated, until the fail2ban-client restarted. 

It seems that the filter tries to get the directory instead of the log file ('/data/logs/linux/current/sshd'), and why fail2ban does not try to open the file again and just stops the processing?

Thanks

***INFO***

[~] fail2ban-client -V
Fail2Ban v0.9.6

[~] cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.8 (Santiago)

[~] uname -a
Linux 2.6.32-642.el6.x86_64 #1 SMP Wed 

[~] fail2ban-client -d
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', 'SYSLOG']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', 86400]
['add', 'sshd', 'auto']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'addlogpath', '/data/logs/linux/current/sshd', 'head']
['set', 'sshd', 'maxretry', 8]
['set', 'sshd', 'addignoreip', '127.0.0.1/8']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'bantime', 1801]
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'findtime', 600]
['set', 'sshd', 'maxlines', '10']

**Comment by sebres** [comment]
Can you take a look in fail2ban.log, which backend (polling, pyinotify, garmin) was selected for sshd in your case.
```bash
?sudo? grep "Jail 'sshd' uses" /var/log/fail2ban.log
```

**Comment by ya-petrov** [comment]
[~] grep "Jail 'sshd' uses" /logs/fail2ban.*
/logs/fail2ban.jail:May 10 00:01:03 fail2ban.jail[24168]: INFO Jail 'sshd' uses pyinotify {}

**Comment by sebres** [comment]
I've fixed there several bugs resp. almost totally rewritten pyinotify-backend in v.10.
If you can test this newer version, [here you are](https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance).
I'll take a look, if I could back-port this to v.9 (but can not promise it will be done, because of possible dependencies and because development of v.9 has been discontinued).

**Comment by ya-petrov** [comment]
I installed the recommended version of the f2b, but the problem is not solved.

[f2b10] grep "Unable" run/fail2ban.log
2017-05-11 06:01:07,725 fail2ban.filter         [11817]: ERROR   Unable to get failures in /data/logs/linux/current/

[f2b10] grep "Jail 'sshd' uses" run/fail2ban.log
2017-05-10 22:25:02,040 fail2ban.jail           [11817]: INFO    Jail 'sshd' uses pyinotify {}

**Comment by sebres** [comment]
Thx, I'll try to reproduce it

**Comment by sebres** [comment]
I assume it is fixed within #1778 now. 
@ya-petrov Would you like to test it?
