### ISSUE TITLE
[Enhancement Request] Wait for log file to exist instead of failing to start

### ISSUE THREAD

**Issue by optix2000** [fail2ban/fail2ban#1789]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.6
- OS, including release name/version: Ubuntu 17.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Currently if a log file doesn't exist when fail2ban starts, fail2ban will fail to start.

This can happen in a few ways, including but not limited to:
- When a service hasn't started yet when fail2ban starts. The log file may not exist if this is the first startup.
- When using rsyslog. When no log lines have been logged to a selector, rsyslog will not create the file until a line is logged.

These are fairly common situations that can prevent fail2ban from starting, and I think such a feature would be worth pursuing.

Thoughts and opinions?

**Comment by sebres** [comment]
The starting in version 0.10 was rewritten, so by missing a logpath fail2ban-client outputs a warning and such jails going idle.
This does not prevent fail2ban-server to start and do proper processing of another jails.

For further logic #1379 was opened.

**Comment by C-Duv** [comment]
So failure to start because of missing file is fixed since 0.10? Not in 0.9.x branch?
(I just upgraded from 0.8.13 to 0.9.6 and discovered `fail2ban` dislikes my non-existing paths)

**Comment by jpveen** [comment]
Sorry to open up an old thread. However it seems that the issue is back in the latest code.
When the log file does not exists I get a failed to start.
My fail2ban version is 0.11.1

`root@ubuntu:/etc/systemd# systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-05-18 08:24:05 CEST; 3s ago
       Docs: man:fail2ban(1)
    Process: 6130 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
    Process: 6131 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 6131 (code=exited, status=255/EXCEPTION)

mei 18 08:24:05 ubuntu systemd[1]: Starting Fail2Ban Service...
mei 18 08:24:05 ubuntu systemd[1]: Started Fail2Ban Service.
mei 18 08:24:05 ubuntu fail2ban-server[6131]: 2022-05-18 08:24:05,657 fail2ban                [6131]: ERROR   Failed during configuration: Have not found any log file for custom_JP jail
mei 18 08:24:05 ubuntu fail2ban-server[6131]: 2022-05-18 08:24:05,658 fail2ban                [6131]: ERROR   Async configuration of server failed
mei 18 08:24:05 ubuntu systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
mei 18 08:24:05 ubuntu systemd[1]: fail2ban.service: Failed with result 'exit-code'.
root@ubuntu:/etc/systemd#
`

**Comment by sebres** [comment]
Hmm... must check that, possibly it still missed a merge with some branch.

**Comment by septatrix** [comment]
I guess you did not come around to checking this yet?
